from collections.abc import Iterable
from typing import Self

class URLError(Exception): ...
class RelativeURLWithoutBase(Exception): ...
class InvalidIPv6Address(Exception): ...
class EmptyHost(Exception): ...
class IdnaError(Exception): ...
class InvalidPort(Exception): ...
class InvalidIPv4Address(Exception): ...
class InvalidDomainCharacter(Exception): ...
class RelativeURLWithCannotBeABaseBase(Exception): ...
class SetHostOnCannotBeABaseURL(Exception): ...

class URL:
    cannot_be_a_base: bool
    host: "Host | None"
    host_str: str | None
    password: str | None
    path: str
    path_segments: Iterable[str] | None
    port: int | None
    scheme: str
    username: str
    fragment: str | None
    query: str | None
    query_pairs: list[tuple[str, str]]

    def __truediv__(self, other: str) -> Self: ...
    @classmethod
    def parse(cls, input: str) -> Self: ...
    @classmethod
    def parse_with_params(
        cls,
        input: str,
        params: Iterable[tuple[str, str]],
    ) -> Self: ...
    def join(self, other: str) -> Self: ...
    def make_relative(self, other: Self) -> str: ...
    def with_fragment(self, fragment: str | None = None) -> Self: ...
    def with_query(self, query: str | None = None) -> Self: ...
    def without_query(self) -> Self: ...
    def with_pair(self, key: str, value: str) -> Self: ...
    def with_key_only(self, key: str) -> Self: ...
    def with_pairs(self, pairs: Iterable[tuple[str, str]]) -> Self: ...
    def with_keys_only(self, keys: Iterable[str]) -> Self: ...
    def without_pair(self, key: str) -> Self: ...

class Host:
    domain: str | None
    ipv4: str | None
    ipv6: str | None
    is_domain: bool
    is_ipv4: bool
    is_ipv6: bool

    def __init__(self, input: str): ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
